//! Search-result reranker.
//!
//! Plan task C.2: given a [`ParsedQuery`] from C.1 and a slice of
//! [`Candidate`]s (Tantivy top-K plus enriched schema fields from C.3),
//! produce a ranked vector with adjusted scores. Pure function, no I/O.
//!
//! Design ref: `docs/plans/2026-05-15-daemon-split-and-search-reranker-design.md` §C.3
//!
//! Boost values are starting points lifted from eros's scorer and will be
//! tuned via the `cargo xtask test dogfood` regression bucket in C.4.

use std::cmp::Ordering;

use crate::extractors::SymbolKind;
use crate::search::query_parse::{ParsedQuery, QueryIntent};

// ---------------------------------------------------------------------------
// Boost weights (tunable; named so they show up in grep when tuning)
// ---------------------------------------------------------------------------

pub(crate) const EXACT_TITLE_BOOST: f32 = 100.0;
pub(crate) const PARTIAL_TITLE_BOOST: f32 = 50.0;
pub(crate) const PATH_BOOST: f32 = 40.0;
pub(crate) const BODY_TERM_BOOST: f32 = 10.0;
pub(crate) const PHRASE_BOOST: f32 = 260.0;
pub(crate) const PHRASE_FILE_DOC_BOOST: f32 = 120.0;
pub(crate) const PHRASE_SOURCE_LANG_BOOST: f32 = 50.0;
pub(crate) const INTENT_TITLE_MATCH_BOOST: f32 = 180.0;
pub(crate) const INTENT_ROLE_MATCH_BOOST: f32 = 120.0;
pub(crate) const PHRASE_MIN_TERMS: usize = 4;

/// Demotion applied to results whose C.3 role is `"vendor"` (e.g.
/// `node_modules/`, `vendor/`). Magnitude chosen so a source partial-title
/// match outranks a vendor exact-title match for "where does this project
/// define X" queries — the dominant fast_search use case.
///
/// Calibration: a vendor exact-title match accumulates the full per-term
/// boost stack: `EXACT_TITLE_BOOST + PATH_BOOST + BODY_TERM_BOOST +
/// kind_boost(Function)` = 100 + 40 + 10 + 60 = 210. A source partial-title
/// match for the same term accumulates `PARTIAL_TITLE_BOOST + PATH_BOOST +
/// BODY_TERM_BOOST` = 50 + 40 + 10 = 100 (no kind_boost — partial-title
/// fails the title-equals-first-term check). For source partial to outrank
/// vendor exact, the penalty must exceed 110. Set to 130 so the swing is
/// firm without burying vendor hits entirely. A vendor exact-title match
/// still nets +80 above zero (210 - 130), so it beats a source non-match
/// (score 0) when the user genuinely needs a vendor symbol.
pub(crate) const VENDOR_PENALTY: f32 = 130.0;

/// Demotion applied to results whose C.3 role is `"generated"` (e.g.
/// `target/`, `dist/`, autogenerated bindings). Same rationale and
/// magnitude as [`VENDOR_PENALTY`].
pub(crate) const GENERATED_PENALTY: f32 = 130.0;

// ---------------------------------------------------------------------------
// Candidate
// ---------------------------------------------------------------------------

/// A single candidate the reranker scores. The fields below mirror what
/// the enriched Tantivy schema (C.3) returns; tests construct candidates
/// via [`Candidate::builder`].
#[derive(Debug, Clone)]
pub struct Candidate {
    pub title: String,
    pub path: String,
    /// Body excerpt — typically the symbol signature + a slice of source.
    /// The reranker lowercases this on the fly; callers can pass the
    /// original capitalization.
    pub body: String,
    pub kind: SymbolKind,
    /// Role per C.3: `"test" | "source" | "docs" | "generated" | "vendor"
    /// | "unknown"`. Stored as String to match the Tantivy schema.
    pub role: String,
    /// Test sub-role per C.3: `"unit" | "integration" | "smoke" | ""`.
    pub test_role: String,
    pub is_test: bool,
    pub is_file_doc: bool,
    pub is_source_language: bool,
    pub tantivy_score: f32,
}

impl Candidate {
    pub fn builder() -> CandidateBuilder {
        CandidateBuilder::default()
    }

    fn kind_matches(&self, kind: &SymbolKind) -> bool {
        &self.kind == kind
    }

    /// True iff at least one target term appears (case-insensitively) in
    /// the title. Lowercased title is passed in so we don't re-allocate
    /// per call.
    fn title_matches_any_term(title_lc: &str, target_terms: &[String]) -> bool {
        target_terms.iter().any(|t| title_lc.contains(t.as_str()))
    }
}

/// Fluent builder for tests and Tantivy result wiring. Defaults populate
/// every field so tests only set what the case under exercise needs.
#[derive(Debug, Clone)]
pub struct CandidateBuilder {
    inner: Candidate,
}

impl Default for CandidateBuilder {
    fn default() -> Self {
        Self {
            inner: Candidate {
                title: String::new(),
                path: String::new(),
                body: String::new(),
                kind: SymbolKind::Function,
                role: "unknown".to_string(),
                test_role: String::new(),
                is_test: false,
                is_file_doc: false,
                is_source_language: false,
                tantivy_score: 0.0,
            },
        }
    }
}

#[allow(dead_code)]
impl CandidateBuilder {
    pub fn title(mut self, v: impl Into<String>) -> Self {
        self.inner.title = v.into();
        self
    }
    pub fn path(mut self, v: impl Into<String>) -> Self {
        self.inner.path = v.into();
        self
    }
    pub fn body(mut self, v: impl Into<String>) -> Self {
        self.inner.body = v.into();
        self
    }
    pub fn kind(mut self, v: SymbolKind) -> Self {
        self.inner.kind = v;
        self
    }
    pub fn role(mut self, v: impl Into<String>) -> Self {
        self.inner.role = v.into();
        self
    }
    pub fn test_role(mut self, v: impl Into<String>) -> Self {
        self.inner.test_role = v.into();
        self
    }
    pub fn is_test(mut self, v: bool) -> Self {
        self.inner.is_test = v;
        self
    }
    pub fn is_file_doc(mut self, v: bool) -> Self {
        self.inner.is_file_doc = v;
        self
    }
    pub fn is_source_language(mut self, v: bool) -> Self {
        self.inner.is_source_language = v;
        self
    }
    pub fn tantivy_score(mut self, v: f32) -> Self {
        self.inner.tantivy_score = v;
        self
    }
    pub fn build(self) -> Candidate {
        self.inner
    }
}

// ---------------------------------------------------------------------------
// Ranked output
// ---------------------------------------------------------------------------

/// One reranked result.
#[derive(Debug, Clone)]
pub struct Ranked {
    pub candidate: Candidate,
    pub final_score: f32,
}

// ---------------------------------------------------------------------------
// Per-kind boost for exact-title matches
// ---------------------------------------------------------------------------

/// Bonus applied when the candidate title equals the first target term
/// exactly. Higher for "primary" symbol kinds; lower for import/export
/// shadows.
pub(crate) fn kind_boost(kind: &SymbolKind) -> f32 {
    use SymbolKind::*;
    match kind {
        Function | Method => 60.0,
        Class | Struct | Trait | Interface => 50.0,
        Enum | Type => 40.0,
        Module | Namespace => 30.0,
        Constant | Variable | Field | Property | EnumMember | Constructor | Destructor
        | Operator | Event | Delegate | Union => 20.0,
        Import | Export => 5.0,
    }
}

// ---------------------------------------------------------------------------
// rerank()
// ---------------------------------------------------------------------------

/// Score every candidate per the C.3 algorithm and return them sorted by
/// `final_score` descending. Ties break on title-asc then path-asc for
/// determinism.
///
/// I4 two-pass behavior: when the query intent is [`QueryIntent::Symbol`] but
/// no candidate satisfies BOTH `kind == requested_kind` AND any-target-term
/// title match, the intent is downgraded to [`QueryIntent::Free`] for the
/// whole batch. This avoids the failure mode where a partial-name same-kind
/// candidate (e.g. `fn user_helper` for query `"function User"`) gets
/// `+INTENT_TITLE_MATCH_BOOST + INTENT_ROLE_MATCH_BOOST` and outranks an
/// exact-name candidate of a different kind (e.g. `class User`).
pub fn rerank(query: &ParsedQuery, candidates: &[Candidate]) -> Vec<Ranked> {
    let effective_query = downgrade_intent_if_unrealized(query, candidates);

    let mut out: Vec<Ranked> = candidates
        .iter()
        .map(|c| Ranked {
            candidate: c.clone(),
            final_score: rerank_symbol_score(&effective_query, c),
        })
        .collect();

    out.sort_by(|a, b| {
        b.final_score
            .partial_cmp(&a.final_score)
            .unwrap_or(Ordering::Equal)
            .then_with(|| a.candidate.title.cmp(&b.candidate.title))
            .then_with(|| a.candidate.path.cmp(&b.candidate.path))
    });

    out
}

/// Score a single symbol candidate without sorting.
///
/// Useful when the caller already has a result list with stable IDs and
/// wants to update each item's score in place, then sort itself.
///
/// **Single-candidate scoring does NOT perform the I4 two-pass intent
/// downgrade** — that decision is a property of the whole candidate batch,
/// and per-candidate callers (the in-place rescorers in `text_search.rs`)
/// apply it themselves via [`rerank_symbol_score_with_effective_intent`].
pub fn rerank_score(query: &ParsedQuery, candidate: &Candidate) -> f32 {
    rerank_symbol_score(query, candidate)
}

/// Score a single symbol candidate. Honors all reranker boosts (title,
/// path, body, phrase, intent, kind, vendor/generated demotion).
pub fn rerank_symbol_score(query: &ParsedQuery, c: &Candidate) -> f32 {
    let title_lc = c.title.to_lowercase();
    let path_lc = c.path.to_lowercase();
    let body_lc = c.body.to_lowercase();
    score_symbol(query, c, &title_lc, &path_lc, &body_lc)
}

/// Score a single content-search candidate. Content results have an empty
/// `body`, a `Module` sentinel `kind`, and no DB-derived `test_role`, so
/// the body/phrase/intent/kind boosts cannot fire usefully. This function
/// applies only the boosts that DO apply to content hits (title and path
/// term boosts, role-based demotion) and explicitly skips the rest. Use
/// this from the content-search reranker entry point so the asymmetry is
/// visible at the type-level rather than hidden in caller construction.
pub fn rerank_content_score(query: &ParsedQuery, c: &Candidate) -> f32 {
    let title_lc = c.title.to_lowercase();
    let path_lc = c.path.to_lowercase();

    let mut score = c.tantivy_score;
    for term in &query.target_terms {
        if title_lc == *term {
            score += EXACT_TITLE_BOOST;
        } else if title_lc.contains(term) {
            score += PARTIAL_TITLE_BOOST;
        }
        if path_lc.contains(term) {
            score += PATH_BOOST;
        }
    }

    // Test-intent role boost still applies: content paths can be classified
    // as test/non-test from `is_test` (path-derived), and a test-intent
    // search that lands on a test file should outrank the same name in
    // production code.
    if matches!(query.intent, QueryIntent::Test)
        && c.is_test
        && Candidate::title_matches_any_term(&title_lc, &query.target_terms)
    {
        score += INTENT_ROLE_MATCH_BOOST;
    }

    score += role_demotion(c);
    score
}

/// Two-pass intent check: if intent is `Symbol(K)` but no candidate has
/// `kind == K` AND a title term match, downgrade to `Free` so the rest of
/// the batch isn't penalized via missing intent boost.
fn downgrade_intent_if_unrealized<'a>(
    query: &'a ParsedQuery,
    candidates: &[Candidate],
) -> std::borrow::Cow<'a, ParsedQuery> {
    let kind = match &query.intent {
        QueryIntent::Symbol(k) => k.clone(),
        _ => return std::borrow::Cow::Borrowed(query),
    };

    let any_realizes = candidates.iter().any(|c| {
        c.kind_matches(&kind) && {
            let title_lc = c.title.to_lowercase();
            Candidate::title_matches_any_term(&title_lc, &query.target_terms)
        }
    });

    if any_realizes {
        std::borrow::Cow::Borrowed(query)
    } else {
        let mut downgraded = query.clone();
        downgraded.intent = QueryIntent::Free;
        std::borrow::Cow::Owned(downgraded)
    }
}

fn score_symbol(
    query: &ParsedQuery,
    c: &Candidate,
    title_lc: &str,
    path_lc: &str,
    body_lc: &str,
) -> f32 {
    let mut score = c.tantivy_score;

    // Per-term boosts: title, path, body.
    for term in &query.target_terms {
        if title_lc == term.as_str() {
            score += EXACT_TITLE_BOOST;
        } else if title_lc.contains(term.as_str()) {
            score += PARTIAL_TITLE_BOOST;
        }
        if path_lc.contains(term.as_str()) {
            score += PATH_BOOST;
        }
        if body_lc.contains(term.as_str()) {
            score += BODY_TERM_BOOST;
        }
    }

    // Phrase boost — only fires when the user gave us enough terms that
    // a contiguous phrase match means something.
    if query.target_terms.len() >= PHRASE_MIN_TERMS {
        let phrase = query.target_terms.join(" ");
        if body_lc.contains(&phrase) {
            score += PHRASE_BOOST;
            if c.is_file_doc {
                score += PHRASE_FILE_DOC_BOOST;
            }
            if c.is_source_language {
                score += PHRASE_SOURCE_LANG_BOOST;
            }
        }
    }

    // Intent boosts.
    match &query.intent {
        QueryIntent::Symbol(kind) => {
            if c.kind_matches(kind)
                && Candidate::title_matches_any_term(title_lc, &query.target_terms)
            {
                score += INTENT_TITLE_MATCH_BOOST;
                if !c.is_test {
                    score += INTENT_ROLE_MATCH_BOOST;
                }
            }
        }
        QueryIntent::Test => {
            if Candidate::title_matches_any_term(title_lc, &query.target_terms) {
                score += INTENT_TITLE_MATCH_BOOST;
                if c.is_test {
                    score += INTENT_ROLE_MATCH_BOOST;
                }
            }
        }
        QueryIntent::Free => {}
    }

    // Kind boost on exact title-equals-first-term match.
    if let Some(first) = query.target_terms.first() {
        if title_lc == first.as_str() {
            score += kind_boost(&c.kind);
        }
    }

    score += role_demotion(c);
    score
}

/// Returns a NEGATIVE adjustment (or zero) for vendored / generated paths.
/// Centralized so the symbol and content scorers stay in sync.
fn role_demotion(c: &Candidate) -> f32 {
    match c.role.as_str() {
        "vendor" => -VENDOR_PENALTY,
        "generated" => -GENERATED_PENALTY,
        _ => 0.0,
    }
}
