//! Search-result reranker.
//!
//! Plan task C.2: given a [`ParsedQuery`] from C.1 and a slice of
//! [`Candidate`]s (Tantivy top-K plus enriched schema fields from C.3),
//! produce a ranked vector with adjusted scores. Pure function, no I/O.
//!
//! Design ref: `docs/plans/2026-05-15-daemon-split-and-search-reranker-design.md` §C.3
//!
//! Boost values are starting points lifted from eros's scorer and will be
//! tuned via the `cargo xtask test dogfood` regression bucket in C.4.

use std::cmp::Ordering;

use crate::extractors::SymbolKind;
use crate::search::query_parse::{ParsedQuery, QueryIntent};

// ---------------------------------------------------------------------------
// Boost weights (tunable; named so they show up in grep when tuning)
// ---------------------------------------------------------------------------

pub(crate) const EXACT_TITLE_BOOST: f32 = 100.0;
pub(crate) const PARTIAL_TITLE_BOOST: f32 = 50.0;
pub(crate) const PATH_BOOST: f32 = 40.0;
pub(crate) const BODY_TERM_BOOST: f32 = 10.0;
pub(crate) const PHRASE_BOOST: f32 = 260.0;
pub(crate) const PHRASE_FILE_DOC_BOOST: f32 = 120.0;
pub(crate) const PHRASE_SOURCE_LANG_BOOST: f32 = 50.0;
pub(crate) const INTENT_TITLE_MATCH_BOOST: f32 = 180.0;
pub(crate) const INTENT_ROLE_MATCH_BOOST: f32 = 120.0;
pub(crate) const PHRASE_MIN_TERMS: usize = 4;

/// Demotion applied to results whose C.3 role is `"vendor"` (e.g.
/// `node_modules/`, `vendor/`). Magnitude chosen so a source partial-title
/// match outranks a vendor exact-title match for "where does this project
/// define X" queries — the dominant fast_search use case.
///
/// Calibration: a vendor exact-title match accumulates the full per-term
/// boost stack: `EXACT_TITLE_BOOST + PATH_BOOST + BODY_TERM_BOOST +
/// kind_boost(Function)` = 100 + 40 + 10 + 60 = 210. A source partial-title
/// match for the same term accumulates `PARTIAL_TITLE_BOOST + PATH_BOOST +
/// BODY_TERM_BOOST` = 50 + 40 + 10 = 100 (no kind_boost — partial-title
/// fails the title-equals-first-term check). For source partial to outrank
/// vendor exact, the penalty must exceed 110. Set to 130 so the swing is
/// firm without burying vendor hits entirely. A vendor exact-title match
/// still nets +80 above zero (210 - 130), so it beats a source non-match
/// (score 0) when the user genuinely needs a vendor symbol.
pub(crate) const VENDOR_PENALTY: f32 = 130.0;

/// Demotion applied to results whose C.3 role is `"generated"` (e.g.
/// `target/`, `dist/`, autogenerated bindings). Same rationale and
/// magnitude as [`VENDOR_PENALTY`].
pub(crate) const GENERATED_PENALTY: f32 = 130.0;

// ---------------------------------------------------------------------------
// Candidate
// ---------------------------------------------------------------------------

/// A single candidate the reranker scores. The fields below mirror what
/// the enriched Tantivy schema (C.3) returns; tests construct candidates
/// via [`Candidate::builder`].
#[derive(Debug, Clone)]
pub struct Candidate {
    pub title: String,
    pub path: String,
    /// Body excerpt — typically the symbol signature + a slice of source.
    /// The reranker lowercases this on the fly; callers can pass the
    /// original capitalization.
    pub body: String,
    pub kind: SymbolKind,
    /// Role per C.3: `"test" | "source" | "docs" | "generated" | "vendor"
    /// | "unknown"`. Stored as String to match the Tantivy schema.
    pub role: String,
    /// Test sub-role per C.3: `"unit" | "integration" | "smoke" | ""`.
    pub test_role: String,
    pub is_test: bool,
    pub is_file_doc: bool,
    pub is_source_language: bool,
    pub tantivy_score: f32,
}

impl Candidate {
    pub fn builder() -> CandidateBuilder {
        CandidateBuilder::default()
    }

    fn kind_matches(&self, kind: &SymbolKind) -> bool {
        &self.kind == kind
    }

    /// True iff at least one target term appears (case-insensitively) in
    /// the title. Lowercased title is passed in so we don't re-allocate
    /// per call.
    fn title_matches_any_term(title_lc: &str, target_terms: &[String]) -> bool {
        target_terms.iter().any(|t| title_lc.contains(t.as_str()))
    }
}

/// Fluent builder for tests and Tantivy result wiring. Defaults populate
/// every field so tests only set what the case under exercise needs.
#[derive(Debug, Clone)]
pub struct CandidateBuilder {
    inner: Candidate,
}

impl Default for CandidateBuilder {
    fn default() -> Self {
        Self {
            inner: Candidate {
                title: String::new(),
                path: String::new(),
                body: String::new(),
                kind: SymbolKind::Function,
                role: "unknown".to_string(),
                test_role: String::new(),
                is_test: false,
                is_file_doc: false,
                is_source_language: false,
                tantivy_score: 0.0,
            },
        }
    }
}

#[allow(dead_code)]
impl CandidateBuilder {
    pub fn title(mut self, v: impl Into<String>) -> Self {
        self.inner.title = v.into();
        self
    }
    pub fn path(mut self, v: impl Into<String>) -> Self {
        self.inner.path = v.into();
        self
    }
    pub fn body(mut self, v: impl Into<String>) -> Self {
        self.inner.body = v.into();
        self
    }
    pub fn kind(mut self, v: SymbolKind) -> Self {
        self.inner.kind = v;
        self
    }
    pub fn role(mut self, v: impl Into<String>) -> Self {
        self.inner.role = v.into();
        self
    }
    pub fn test_role(mut self, v: impl Into<String>) -> Self {
        self.inner.test_role = v.into();
        self
    }
    pub fn is_test(mut self, v: bool) -> Self {
        self.inner.is_test = v;
        self
    }
    pub fn is_file_doc(mut self, v: bool) -> Self {
        self.inner.is_file_doc = v;
        self
    }
    pub fn is_source_language(mut self, v: bool) -> Self {
        self.inner.is_source_language = v;
        self
    }
    pub fn tantivy_score(mut self, v: f32) -> Self {
        self.inner.tantivy_score = v;
        self
    }
    pub fn build(self) -> Candidate {
        self.inner
    }
}

// ---------------------------------------------------------------------------
// Ranked output
// ---------------------------------------------------------------------------

/// One reranked result.
#[derive(Debug, Clone)]
pub struct Ranked {
    pub candidate: Candidate,
    pub final_score: f32,
}

// ---------------------------------------------------------------------------
// Per-kind boost for exact-title matches
// ---------------------------------------------------------------------------

/// Bonus applied when the candidate title equals the first target term
/// exactly. Higher for "primary" symbol kinds; lower for import/export
/// shadows.
pub(crate) fn kind_boost(kind: &SymbolKind) -> f32 {
    use SymbolKind::*;
    match kind {
        Function | Method => 60.0,
        Class | Struct | Trait | Interface => 50.0,
        Enum | Type => 40.0,
        Module | Namespace => 30.0,
        Constant | Variable | Field | Property | EnumMember | Constructor | Destructor
        | Operator | Event | Delegate | Union => 20.0,
        Import | Export => 5.0,
    }
}

// ---------------------------------------------------------------------------
// rerank()
// ---------------------------------------------------------------------------

/// Two-pass intent check: if intent is `Symbol(K)` but no candidate has
/// `kind == K` AND a title term match, downgrade to `Free` so the rest of
/// the batch isn't penalized via missing intent boost.
fn downgrade_intent_if_unrealized<'a>(
    query: &'a ParsedQuery,
    candidates: &[Candidate],
) -> std::borrow::Cow<'a, ParsedQuery> {
    let kind = match &query.intent {
        QueryIntent::Symbol(k) => k.clone(),
        _ => return std::borrow::Cow::Borrowed(query),
    };

    let any_realizes = candidates.iter().any(|c| {
        c.kind_matches(&kind) && {
            let title_lc = c.title.to_lowercase();
            Candidate::title_matches_any_term(&title_lc, &query.target_terms)
        }
    });

    if any_realizes {
        std::borrow::Cow::Borrowed(query)
    } else {
        let mut downgraded = query.clone();
        downgraded.intent = QueryIntent::Free;
        std::borrow::Cow::Owned(downgraded)
    }
}

fn score_symbol(
    query: &ParsedQuery,
    c: &Candidate,
    title_lc: &str,
    path_lc: &str,
    body_lc: &str,
) -> f32 {
    let mut score = c.tantivy_score;

    // Per-term boosts: title, path, body.
    for term in &query.target_terms {
        if title_lc == term.as_str() {
            score += EXACT_TITLE_BOOST;
        } else if title_lc.contains(term.as_str()) {
            score += PARTIAL_TITLE_BOOST;
        }
        if path_lc.contains(term.as_str()) {
            score += PATH_BOOST;
        }
        if body_lc.contains(term.as_str()) {
            score += BODY_TERM_BOOST;
        }
    }

    // Phrase boost — only fires when the user gave us enough terms that
    // a contiguous phrase match means something.
    if query.target_terms.len() >= PHRASE_MIN_TERMS {
        let phrase = query.target_terms.join(" ");
        if body_lc.contains(&phrase) {
            score += PHRASE_BOOST;
            if c.is_file_doc {
                score += PHRASE_FILE_DOC_BOOST;
            }
            if c.is_source_language {
                score += PHRASE_SOURCE_LANG_BOOST;
            }
        }
    }

    // Intent boosts.
    match &query.intent {
        QueryIntent::Symbol(kind) => {
            if c.kind_matches(kind)
                && Candidate::title_matches_any_term(title_lc, &query.target_terms)
            {
                score += INTENT_TITLE_MATCH_BOOST;
                if !c.is_test {
                    score += INTENT_ROLE_MATCH_BOOST;
                }
            }
        }
        QueryIntent::Test => {
            if Candidate::title_matches_any_term(title_lc, &query.target_terms) {
                score += INTENT_TITLE_MATCH_BOOST;
                if c.is_test {
                    score += INTENT_ROLE_MATCH_BOOST;
                }
            }
        }
        QueryIntent::Free => {}
    }

    // Kind boost on exact title-equals-first-term match.
    if let Some(first) = query.target_terms.first() {
        if title_lc == first.as_str() {
            score += kind_boost(&c.kind);
        }
    }

    score += role_demotion(c);
    score
}

/// Returns a NEGATIVE adjustment (or zero) for vendored / generated paths.
/// Centralized so the symbol and content scorers stay in sync.
fn role_demotion(c: &Candidate) -> f32 {
    match c.role.as_str() {
        "vendor" => -VENDOR_PENALTY,
        "generated" => -GENERATED_PENALTY,
        _ => 0.0,
    }
}

// ---------------------------------------------------------------------------
// rerank_unified — T6 Eros-recipe field-score boosts on mixed-kind candidates
// ---------------------------------------------------------------------------

/// Boost applied to a file row whose basename (or stem) exactly matches the
/// compact-normalised query.  Chosen to be larger than the symbol exact-title
/// path so a file named `browser_client.py` dominates a symbol at some
/// unrelated path that merely mentions `browser_client` in a path fragment.
pub(crate) const FILE_BASENAME_EXACT_BOOST: f32 = 120.0;

/// Boost applied to a file row per term when the term exactly matches the
/// file's basename (no extension).
pub(crate) const FILE_BASENAME_TERM_BOOST: f32 = 30.0;

/// Per-term path-fragment boost for symbol rows (smaller than PATH_BOOST to
/// avoid over-rewarding coincidental path fragments).
pub(crate) const PATH_FRAGMENT_BOOST: f32 = 25.0;

/// Per-term basename exact-match boost (file rows and symbol rows).
pub(crate) const BASENAME_EXACT_TERM_BOOST: f32 = 40.0;

/// Fixed kind bonus for file rows when the full-string compact match fires
/// (analogous to `kind_boost` for symbol rows, but file rows have no
/// SymbolKind to dispatch on).
pub(crate) const FILE_KIND_EXACT_BONUS: f32 = 30.0;

/// Boost applied when a query exactly matches a path-segment of a file row's
/// path (between `/` separators).  This handles cases like query=".cargo"
/// matching the path ".cargo/config.toml" where the dot-prefixed directory
/// name is the load-bearing identifier and compact-normalisation would strip
/// the dot.  Large enough to overcome basename-stem matches against shallower
/// peers (e.g., ranking ".cargo/config.toml" above "Cargo.toml" for query
/// ".cargo").
pub(crate) const FILE_PATH_SEGMENT_EXACT_BOOST: f32 = 160.0;

/// Rerank a mixed slice of symbol and file-row candidates using the
/// Eros-recipe field-score boosts.
///
/// This is the T6 entry point for `execute_search_unified` (and
/// `search_unified` in `index.rs`).  It handles both symbol rows
/// (`is_file_doc == false`) and file rows (`is_file_doc == true`) in a single
/// pass, absorbing the logic that the Phase-1 cross-target helpers
/// (`apply_symbol_title_boost_to_file_results`,
/// `apply_reranker_to_content_results` title-exact block) performed on
/// separate result sets.
///
/// This replaces the per-target per-result scalar functions and the standalone
/// Phase-1 helpers deleted in T9 cleanup.
///
/// Scoring formula per candidate:
/// ```
/// final = tantivy_score
///       + full_string_boost(c)     // compact whole-query match on title/basename
///       + per_term_boosts(c)       // title, path, basename per query term
///       + role_demotion(c)         // vendor / generated penalty (negative)
/// ```
pub fn rerank_unified(query: &ParsedQuery, candidates: &[Candidate]) -> Vec<Ranked> {
    use crate::search::index::compact_alnum_lc;

    let query_compact = compact_alnum_lc(&query.raw);

    let mut ranked: Vec<Ranked> = candidates
        .iter()
        .map(|c| {
            let mut score = c.tantivy_score;

            let title_lc = c.title.to_lowercase();
            let path_lc = c.path.to_lowercase();

            // ── Full-string compact match ─────────────────────────────────
            // Compact-form normalisation strips non-alphanumerics and
            // lowercases so that `BrowserClient`, `browser_client`, and
            // `browser client` all normalise to `browserclient`.
            let title_compact = compact_alnum_lc(&c.title);

            if c.is_file_doc {
                // File row: check basename (with and without extension).
                let basename_lc = path_lc
                    .rsplit('/')
                    .next()
                    .unwrap_or(path_lc.as_str())
                    .to_string();
                let stem_lc: &str = basename_lc
                    .rsplit_once('.')
                    .map(|(s, _)| s)
                    .unwrap_or(&basename_lc);
                let basename_compact = compact_alnum_lc(&basename_lc);
                let stem_compact = compact_alnum_lc(stem_lc);

                // Path-segment-exact: query matches a `/`-separated path
                // component verbatim.  Catches dot-prefixed directories like
                // ".cargo" in ".cargo/config.toml" that compact_alnum_lc
                // would otherwise strip into a sibling-collision with
                // "Cargo.toml".
                let query_raw_lc = query.raw.to_lowercase();
                let path_segment_exact = !query_raw_lc.is_empty()
                    && path_lc
                        .split('/')
                        .any(|segment| segment == query_raw_lc);
                if path_segment_exact {
                    score += FILE_PATH_SEGMENT_EXACT_BOOST;
                }

                if !query_compact.is_empty()
                    && (basename_compact == query_compact || stem_compact == query_compact)
                {
                    // Exact basename/stem match — strongest file-row signal.
                    score += FILE_BASENAME_EXACT_BOOST + FILE_KIND_EXACT_BONUS;
                } else if !query_compact.is_empty() && title_compact == query_compact {
                    // Title compact match (title field on file rows carries the
                    // file name stored by the indexer).
                    score += EXACT_TITLE_BOOST + FILE_KIND_EXACT_BONUS;
                }
            }
            // Symbol row: compact match on symbol name handles
            // CamelCase↔snake_case cross-style matches like query
            // "BrowserClient" → symbol `browser_client` that the
            // per-term branch can't catch.  Only fires when per-term
            // can't ALREADY add the same boosts (i.e. when the first
            // target term doesn't equal title_lc); otherwise the
            // per-term branch already contributes EXACT_TITLE_BOOST and
            // first-term-kind_boost would double-count below.
            let mut symbol_compact_fired = false;
            if !c.is_file_doc
                && !query_compact.is_empty()
                && title_compact == query_compact
            {
                let per_term_will_match_title = query
                    .target_terms
                    .iter()
                    .any(|t| title_lc == t.as_str());
                if !per_term_will_match_title {
                    score += EXACT_TITLE_BOOST + kind_boost(&c.kind);
                    symbol_compact_fired = true;
                }
            }

            // ── Per-term boosts ───────────────────────────────────────────
            // Title / path / body matching is applied to both symbol and file
            // rows.  File rows additionally get basename-exact boosts.
            // Symbol rows use PATH_BOOST (40); file rows use the smaller
            // PATH_FRAGMENT_BOOST (25) because their path is already covered
            // by the dedicated basename boosts above.
            let body_lc = c.body.to_lowercase();
            for term in &query.target_terms {
                let term_s = term.as_str();
                let term_compact = compact_alnum_lc(term_s);

                if title_lc == term_s {
                    score += EXACT_TITLE_BOOST;
                } else if title_lc.contains(term_s) {
                    score += PARTIAL_TITLE_BOOST;
                }
                if path_lc.contains(term_s) {
                    if c.is_file_doc {
                        score += PATH_FRAGMENT_BOOST;
                    } else {
                        score += PATH_BOOST;
                    }
                }
                if !body_lc.is_empty() && body_lc.contains(term_s) {
                    score += BODY_TERM_BOOST;
                }

                if c.is_file_doc {
                    // Basename exact: term matches the basename stem.
                    let basename_lc_for_term = path_lc
                        .rsplit('/')
                        .next()
                        .unwrap_or(path_lc.as_str())
                        .to_string();
                    let stem_for_term: &str = basename_lc_for_term
                        .rsplit_once('.')
                        .map(|(s, _)| s)
                        .unwrap_or(&basename_lc_for_term);
                    if !term_compact.is_empty()
                        && compact_alnum_lc(stem_for_term) == term_compact
                    {
                        score += FILE_BASENAME_TERM_BOOST;
                    }
                    // Basename exact (full, with extension).
                    if !term_compact.is_empty()
                        && compact_alnum_lc(&basename_lc_for_term) == term_compact
                    {
                        score += BASENAME_EXACT_TERM_BOOST;
                    }
                }
            }

            // ── Phrase boost (4+ target terms; body contains contiguous phrase)
            // Mirrors the per-target `score_symbol` phrase rule.  Applies to
            // both symbol and file rows so a query like "alpha beta gamma
            // delta" appearing verbatim in a body or content boosts that
            // candidate above ones that only have the individual terms.
            if query.target_terms.len() >= PHRASE_MIN_TERMS {
                let phrase = query.target_terms.join(" ");
                let phrase_in_body = !body_lc.is_empty() && body_lc.contains(&phrase);
                if phrase_in_body {
                    score += PHRASE_BOOST;
                    if c.is_file_doc {
                        score += PHRASE_FILE_DOC_BOOST;
                    }
                    if c.is_source_language {
                        score += PHRASE_SOURCE_LANG_BOOST;
                    }
                }
            }

            // ── Intent boosts (symbol rows only) ─────────────────────────
            // Mirrors the per-target `score_symbol` intent-routing so that
            // test-intent queries promote test symbols and kind-intent queries
            // promote kind-matched symbols in the unified path.
            if !c.is_file_doc {
                match &query.intent {
                    QueryIntent::Test => {
                        if Candidate::title_matches_any_term(&title_lc, &query.target_terms) {
                            score += INTENT_TITLE_MATCH_BOOST;
                            if c.is_test {
                                score += INTENT_ROLE_MATCH_BOOST;
                            }
                        }
                    }
                    QueryIntent::Symbol(kind) => {
                        if c.kind_matches(kind)
                            && Candidate::title_matches_any_term(&title_lc, &query.target_terms)
                        {
                            score += INTENT_TITLE_MATCH_BOOST;
                            if !c.is_test {
                                score += INTENT_ROLE_MATCH_BOOST;
                            }
                        }
                    }
                    QueryIntent::Free => {}
                }

                // First-term kind boost — mirrors the per-target
                // `score_symbol` rule: when the candidate's title exactly
                // matches the first target term, add a kind-specific bonus.
                // Skip if the full-string compact branch already added
                // `kind_boost` (avoids double-counting for queries where the
                // compact form equals the first term and the title).
                if !symbol_compact_fired {
                    if let Some(first) = query.target_terms.first() {
                        if title_lc == first.as_str() {
                            score += kind_boost(&c.kind);
                        }
                    }
                }
            }

            // ── Role demotion ─────────────────────────────────────────────
            score += role_demotion(c);

            Ranked {
                candidate: c.clone(),
                final_score: score,
            }
        })
        .collect();

    // Sort descending by final_score, then by title for stability.
    ranked.sort_by(|a, b| {
        b.final_score
            .partial_cmp(&a.final_score)
            .unwrap_or(Ordering::Equal)
            .then_with(|| a.candidate.title.cmp(&b.candidate.title))
    });

    ranked
}
