//! Shared embedding contract types — the trait and its companion structs.
//!
//! Lives here in `julie-core` (the bottom leaf crate) so that both the main
//! `julie` crate and any future sibling crates can depend on a single
//! definition. The `julie::embeddings` module re-exports everything from here,
//! so all existing `crate::embeddings::*` import paths remain valid.

use anyhow::{Result, bail};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

pub use crate::embeddings_identity::EncoderIdentity;

/// Semantic retrieval execution mode across CLI and MCP transports.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, schemars::JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum SemanticMode {
    #[default]
    Auto,
    Off,
    Required,
}

impl SemanticMode {
    pub fn is_off(&self) -> bool {
        matches!(self, Self::Off)
    }

    pub fn is_required(&self) -> bool {
        matches!(self, Self::Required)
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Auto => "auto",
            Self::Off => "off",
            Self::Required => "required",
        }
    }
}

/// Query embedding tagged with the generating encoder key and source revision.
///
/// Ensures readers only compare vectors generated by the same encoder model
/// against the same workspace revision, preventing torn reads and mixed-model KNN comparisons.
#[derive(Clone, Debug, PartialEq)]
pub struct TaggedQueryEmbedding {
    pub vector: Vec<f32>,
    pub encoder_key: String,
    pub source_revision: i64,
}

impl TaggedQueryEmbedding {
    pub fn new(vector: Vec<f32>, encoder_key: impl Into<String>, source_revision: i64) -> Self {
        Self {
            vector,
            encoder_key: encoder_key.into(),
            source_revision,
        }
    }

    pub fn untagged(vector: Vec<f32>) -> Self {
        Self {
            vector,
            encoder_key: String::new(),
            source_revision: 0,
        }
    }

    pub fn is_tagged(&self) -> bool {
        !self.encoder_key.is_empty()
    }
}

impl From<Vec<f32>> for TaggedQueryEmbedding {
    fn from(vector: Vec<f32>) -> Self {
        Self::untagged(vector)
    }
}

/// Current SQLite vector storage format version.
pub const CURRENT_EMBEDDING_FORMAT_VERSION: u32 = 3;

/// Per-request execution budget for embedding operations.
///
/// Propagated to all provider calls (`embed_query`, `embed_batch`) to bound
/// connection, lock admission, socket I/O, and batch processing without relying
/// on mutable process-global state.
#[derive(Clone, Debug)]
pub struct EmbeddingRequestBudget {
    pub deadline: Instant,
    pub cancelled: Arc<AtomicBool>,
}

impl EmbeddingRequestBudget {
    /// Creates a new budget with an explicit deadline and cancellation handle.
    pub fn new(deadline: Instant, cancelled: Arc<AtomicBool>) -> Self {
        Self {
            deadline,
            cancelled,
        }
    }

    /// Creates a new uncancelled budget with a timeout relative to `Instant::now()`.
    pub fn with_timeout(timeout: Duration) -> Self {
        Self {
            deadline: Instant::now() + timeout,
            cancelled: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Convenience alias for with_timeout.
    pub fn from_timeout(timeout: Duration) -> Self {
        Self::with_timeout(timeout)
    }

    /// Creates an effectively unbounded budget (1 year deadline, not cancelled).
    pub fn unbounded() -> Self {
        Self {
            deadline: Instant::now() + Duration::from_secs(365 * 24 * 3600),
            cancelled: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Checks if cancellation has been requested.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }

    /// Checks if the deadline has passed.
    pub fn is_expired(&self) -> bool {
        Instant::now() >= self.deadline
    }

    /// Returns the remaining duration until the deadline, saturated to `Duration::ZERO`.
    pub fn remaining_time(&self) -> Duration {
        self.deadline.saturating_duration_since(Instant::now())
    }

    /// Returns the remaining duration if not expired, or `None` if the deadline has passed.
    pub fn remaining_time_checked(&self) -> Option<Duration> {
        self.deadline.checked_duration_since(Instant::now())
    }

    /// Alias for remaining_time_checked.
    pub fn remaining(&self) -> Option<Duration> {
        self.remaining_time_checked()
    }

    /// Returns `Ok(())` if the request is still within budget, or an error if
    /// cancelled or timed out.
    pub fn check_budget(&self) -> Result<()> {
        if self.is_cancelled() {
            bail!("embedding request cancelled");
        }
        if self.is_expired() {
            bail!("embedding request deadline exceeded");
        }
        Ok(())
    }

    /// Alias for check_budget.
    pub fn check(&self) -> Result<()> {
        self.check_budget()
    }

    /// Convenience constructor for test cases (30-second default timeout).
    pub fn for_testing() -> Self {
        Self::with_timeout(Duration::from_secs(30))
    }

    /// Requests cancellation of operations observing this budget.
    pub fn cancel(&self) {
        self.cancelled.store(true, Ordering::Release);
    }
}

impl Default for EmbeddingRequestBudget {
    fn default() -> Self {
        Self::unbounded()
    }
}

/// Supported embedding backends.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmbeddingBackend {
    Auto,
    Native,
    Unresolved,
    Invalid(String),
}

impl EmbeddingBackend {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Auto => "auto",
            Self::Native => "native",
            Self::Unresolved => "unresolved",
            Self::Invalid(_) => "invalid",
        }
    }
}

/// Runtime status for embedding initialization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmbeddingRuntimeStatus {
    pub requested_backend: EmbeddingBackend,
    pub resolved_backend: EmbeddingBackend,
    pub accelerated: bool,
    pub degraded_reason: Option<String>,
}

/// Information about the embedding device/runtime.
#[derive(Debug, Clone)]
pub struct DeviceInfo {
    pub runtime: String,
    pub device: String,
    pub model_name: String,
    pub dimensions: usize,
}

impl DeviceInfo {
    /// Best-effort hardware acceleration detection for diagnostics.
    pub fn is_accelerated(&self) -> bool {
        let combined = format!(
            "{} {}",
            self.runtime.to_ascii_lowercase(),
            self.device.to_ascii_lowercase()
        );

        if combined.contains("cpu") {
            return false;
        }

        [
            "gpu", "cuda", "rocm", "mps", "metal", "directml", "dml", "vulkan", "coreml",
        ]
        .iter()
        .any(|hint| combined.contains(hint))
    }
}

/// Trait abstracting vector embedding generation.
///
/// Implementations must be `Send + Sync` for use behind `Arc` in async contexts.
/// The trait uses `&self`; implementors are expected to use interior mutability
/// (e.g., `Mutex`) if their underlying runtime requires `&mut self`.
pub trait EmbeddingProvider: Send + Sync {
    /// Embed a single query string within the supplied budget. Returns a vector of `dimensions()` floats.
    fn embed_query(&self, text: &str, budget: &EmbeddingRequestBudget) -> Result<Vec<f32>>;

    /// Embed a batch of texts within the supplied budget. Returns one vector per input text.
    fn embed_batch(
        &self,
        texts: &[String],
        budget: &EmbeddingRequestBudget,
    ) -> Result<Vec<Vec<f32>>>;

    /// Complete cryptographic identity of the active encoder.
    fn encoder_identity(&self) -> Result<EncoderIdentity>;

    /// The dimensionality of produced embeddings (e.g., 384 for BGE-small).
    fn dimensions(&self) -> usize;

    /// Runtime and device information for diagnostics.
    fn device_info(&self) -> DeviceInfo;

    /// Provider-reported acceleration state, if known.
    fn accelerated(&self) -> Option<bool> {
        None
    }

    /// Provider-reported degraded runtime reason, if known.
    fn degraded_reason(&self) -> Option<String> {
        None
    }

    /// Running executable SHA-256 digest reported by the active provider, if applicable.
    fn running_executable_sha(&self) -> Option<String> {
        None
    }

    /// Verify provider health and connection liveness.
    /// Default implementation returns `Ok(())` for mock or in-memory providers.
    fn health_check(&self, _budget: &EmbeddingRequestBudget) -> Result<()> {
        Ok(())
    }

    /// Explicitly shut down the provider, releasing any child processes.
    /// Default is a no-op; the native provider overrides to shut down its sidecar child.
    fn shutdown(&self) {}

    /// Wait for the provider's underlying child process to exit, up to `timeout`.
    ///
    /// Returns `true` if the child exited within the timeout, `false` if the
    /// timeout elapsed before the child exited. Providers without a child
    /// process return `true` immediately (no-op default).
    ///
    /// This is a blocking call. Callers in async context should run it via
    /// `tokio::task::spawn_blocking`.
    fn wait_for_exit(&self, _timeout: Duration) -> bool {
        true
    }

    /// Returns the OS process ID of the active sidecar child, if running.
    fn child_pid(&self) -> Option<u32> {
        None
    }
}

