//! Indexable-file discovery coverage.

use super::*;

#[test]
fn test_discover_indexable_files_creates_julieignore_for_blacklisted_vendor_dirs() {
    let tool = create_tool();

    // Create workspace with target/ directory (blacklisted AND vendor pattern)
    let (temp_dir, _files) = create_workspace_with_files(vec![
        "src/main.rs",
        "src/lib.rs",
        "target/debug/deps/file1.rlib",
        "target/debug/deps/file2.rlib",
        "target/debug/deps/file3.rlib",
        "target/debug/deps/file4.rlib",
        "target/debug/deps/file5.rlib",
        "target/debug/deps/file6.rlib", // >5 files should trigger vendor detection
        "target/debug/deps/file7.rlib",
        "target/debug/deps/file8.rlib",
    ]);

    // Call discover_indexable_files (simulates first workspace scan)
    let _indexable_files = tool
        .discover_indexable_files(temp_dir.path())
        .expect("Failed to discover files");

    // Verify .julieignore was created
    let julieignore_path = temp_dir.path().join(".julieignore");
    assert!(
        julieignore_path.exists(),
        "Expected .julieignore to be created for blacklisted vendor directory target/"
    );

    // Verify it contains the target/ pattern
    let content = std::fs::read_to_string(&julieignore_path).expect("Failed to read .julieignore");

    assert!(
        content.contains("target/"),
        "Expected .julieignore to contain 'target/' pattern. Content:\n{}",
        content
    );
}

#[test]
fn test_discover_creates_julieignore_even_without_vendor_patterns() {
    let tool = create_tool();

    // Clean project: just source files, no vendor directories at all
    let (temp_dir, _files) =
        create_workspace_with_files(vec!["src/main.rs", "src/lib.rs", "src/utils.rs"]);

    let _indexable = tool
        .discover_indexable_files(temp_dir.path())
        .expect("Failed to discover files");

    // .julieignore must be created even with zero vendor patterns
    let julieignore_path = temp_dir.path().join(".julieignore");
    assert!(
        julieignore_path.exists(),
        "Expected .julieignore to be created even when no vendor patterns are detected"
    );

    // Verify it's a valid template (has the header, no active patterns)
    let content = std::fs::read_to_string(&julieignore_path).expect("Failed to read .julieignore");
    assert!(
        content.contains("Auto-generated by Julie"),
        "Expected .julieignore to contain the auto-generated header"
    );
    // No active (uncommented) patterns since no vendor dirs were found
    let active_patterns: Vec<&str> = content
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .collect();
    assert!(
        active_patterns.is_empty(),
        "Expected no active patterns in .julieignore for clean project, found: {:?}",
        active_patterns
    );
}

#[test]
fn test_memories_dir_excluded_from_discovery() {
    let tool = create_tool();
    let (temp_dir, _) = create_workspace_with_files(vec![
        "src/main.rs",
        "src/lib.rs",
        ".memories/checkpoint_abc123.md",
        ".memories/checkpoint_def456.md",
    ]);

    let indexable = tool
        .discover_indexable_files(temp_dir.path())
        .expect("Failed to discover files");

    // .memories files should not be discovered — they are non-code memory artifacts
    let memory_files: Vec<_> = indexable
        .iter()
        .filter(|p| p.to_string_lossy().contains(".memories"))
        .collect();

    assert!(
        memory_files.is_empty(),
        "Expected .memories files to be excluded from discovery"
    );

    // Verify actual source files ARE also discovered
    let rs_files: Vec<_> = indexable
        .iter()
        .filter(|p| p.extension().map_or(false, |e| e == "rs"))
        .collect();
    assert_eq!(rs_files.len(), 2, "Should discover both .rs source files");
}

#[test]
fn test_discover_indexable_files_respects_gitignore() {
    let tool = create_tool();
    let temp_dir = tempfile::TempDir::new().unwrap();
    let root = temp_dir.path();
    // Need .git dir for gitignore to be recognized
    std::fs::create_dir_all(root.join(".git")).unwrap();
    std::fs::write(root.join(".gitignore"), "generated/\n").unwrap();
    std::fs::create_dir_all(root.join("generated")).unwrap();
    std::fs::write(root.join("generated/api.rs"), "// generated").unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(root.join("src/main.rs"), "fn main() {}").unwrap();

    let files = tool.discover_indexable_files(root).unwrap();
    let paths: Vec<String> = files
        .iter()
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .collect();
    assert!(
        paths.iter().any(|p| p.contains("main.rs")),
        "should include src/main.rs"
    );
    assert!(
        !paths.iter().any(|p| p.contains("generated")),
        "should exclude gitignored generated/"
    );
}
