//! `.julieignore` generation coverage.

use super::*;

#[test]
fn test_generate_julieignore_file_creates_file_with_correct_format() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_path = temp_dir.path();

    let patterns = vec!["Scripts/libs".to_string(), "Scripts/plugin".to_string()];

    tool.generate_julieignore_file(workspace_path, &patterns)
        .expect("Failed to generate .julieignore");

    let julieignore_path = workspace_path.join(".julieignore");
    assert!(julieignore_path.exists(), ".julieignore should be created");

    let content = std::fs::read_to_string(&julieignore_path).expect("Failed to read .julieignore");

    // Verify patterns end with "/" not "/**"
    assert!(
        content.contains("Scripts/libs/"),
        "Pattern should end with /"
    );
    assert!(
        content.contains("Scripts/plugin/"),
        "Pattern should end with /"
    );
    assert!(
        !content.contains("Scripts/libs/**"),
        "Pattern should NOT contain /**"
    );
    assert!(
        !content.contains("Scripts/plugin/**"),
        "Pattern should NOT contain /**"
    );

    // Verify header documentation exists
    assert!(content.contains("# .julieignore - Julie Code Intelligence Exclusion Patterns"));
    assert!(content.contains("Auto-generated by Julie on"));

    // Verify usage instructions exist
    assert!(content.contains("What Julie Did Automatically"));
    assert!(content.contains("Why Exclude Vendor Code?"));
    assert!(content.contains("How to Modify This File"));
}

#[test]
fn test_generate_julieignore_file_includes_date() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_path = temp_dir.path();

    let patterns = vec!["vendor".to_string()];

    tool.generate_julieignore_file(workspace_path, &patterns)
        .expect("Failed to generate .julieignore");

    let content = std::fs::read_to_string(workspace_path.join(".julieignore"))
        .expect("Failed to read .julieignore");

    // Should contain current date in YYYY-MM-DD format
    let date_regex = regex::Regex::new(r"\d{4}-\d{2}-\d{2}").unwrap();
    assert!(date_regex.is_match(&content), "Should include current date");
}

#[test]
fn test_generate_julieignore_file_empty_patterns() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_path = temp_dir.path();

    let patterns: Vec<String> = vec![];

    tool.generate_julieignore_file(workspace_path, &patterns)
        .expect("Failed to generate .julieignore");

    let content = std::fs::read_to_string(workspace_path.join(".julieignore"))
        .expect("Failed to read .julieignore");

    // Should still create file with documentation, just no patterns
    assert!(content.contains("# .julieignore"));
    assert!(content.contains("Auto-Detected Vendor Directories"));
}

#[test]
fn test_dir_to_pattern_strips_workspace_prefix() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_root = temp_dir.path();

    let dir = workspace_root.join("Scripts/libs");

    let pattern = tool.dir_to_pattern(&dir, workspace_root);

    assert_eq!(pattern, "Scripts/libs", "Should strip workspace prefix");
}

#[test]
fn test_dir_to_pattern_normalizes_backslashes() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_root = temp_dir.path();

    // Simulate Windows path with backslashes
    let dir = workspace_root.join("Scripts").join("libs");

    let pattern = tool.dir_to_pattern(&dir, workspace_root);

    // Should use forward slashes regardless of platform
    assert!(pattern.contains("/"), "Should use forward slashes");
    assert!(!pattern.contains("\\"), "Should NOT contain backslashes");
}

#[test]
fn test_dir_to_pattern_handles_nested_directories() {
    let tool = create_tool();
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let workspace_root = temp_dir.path();

    let dir = workspace_root.join("src/vendor/libs/external");

    let pattern = tool.dir_to_pattern(&dir, workspace_root);

    assert_eq!(
        pattern, "src/vendor/libs/external",
        "Should handle nested paths"
    );
}

#[test]
fn test_vendor_detection_full_workflow() {
    let tool = create_tool();
    let (temp_dir, files) = create_workspace_with_files(vec![
        // Vendor directory (vendor/)
        "Scripts/vendor/jquery.js",
        "Scripts/vendor/bootstrap.js",
        "Scripts/vendor/angular.js",
        "Scripts/vendor/lodash.js",
        "Scripts/vendor/moment.js",
        "Scripts/vendor/axios.js",
        // Custom code (should NOT be detected)
        "Scripts/PatientCase.js",
        "Scripts/Scheduling.js",
    ]);

    // Step 1: Analyze for patterns
    let patterns = tool
        .analyze_vendor_patterns(&files, temp_dir.path())
        .expect("Failed to analyze patterns");

    assert_eq!(patterns.len(), 1, "Should detect 1 vendor directory");
    assert_eq!(patterns[0], "Scripts/vendor");

    // Step 2: Generate .julieignore
    tool.generate_julieignore_file(temp_dir.path(), &patterns)
        .expect("Failed to generate .julieignore");

    // Step 3: Verify file created with correct format
    let julieignore_path = temp_dir.path().join(".julieignore");
    assert!(julieignore_path.exists());

    let content = std::fs::read_to_string(&julieignore_path).expect("Failed to read .julieignore");

    assert!(
        content.contains("Scripts/vendor/"),
        "Should have correct pattern format"
    );
    assert!(
        !content.contains("Scripts/vendor/**"),
        "Should NOT use /** format"
    );
}
