use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::tree_sitter_real_world::DEFAULT_TREE_SITTER_REAL_WORLD_EVIDENCE;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TreeSitterRealWorldEvidenceReport {
    pub profile: String,
    pub julie_head: String,
    pub corpus_path: String,
    pub verified_repos: Vec<TreeSitterRealWorldRepoEvidence>,
    pub skipped_repos: Vec<TreeSitterRealWorldSkippedRepo>,
    pub summary_flags: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TreeSitterRealWorldRepoEvidence {
    pub repo_name: String,
    pub language: String,
    pub display_path: String,
    pub repo_head: Option<String>,
    pub workspace_id: String,
    pub file_count: i64,
    pub language_file_count: i64,
    pub symbol_count: i64,
    pub relationship_count: i64,
    pub identifier_count: i64,
    pub type_count: i64,
    pub parse_diagnostic_file_count: i64,
    pub status: String,
    pub hard_failures: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TreeSitterRealWorldSkippedRepo {
    pub repo_name: String,
    pub language: String,
    pub reason: String,
}

pub fn load_tree_sitter_real_world_evidence(
    root: &Path,
) -> Result<Option<TreeSitterRealWorldEvidenceReport>> {
    let path = root.join(DEFAULT_TREE_SITTER_REAL_WORLD_EVIDENCE);
    if !path.exists() {
        return Ok(None);
    }

    let text = fs::read_to_string(&path)
        .with_context(|| format!("failed to read real-world evidence at {}", path.display()))?;
    let report = serde_json::from_str(&text)
        .with_context(|| format!("failed to parse real-world evidence at {}", path.display()))?;
    Ok(Some(report))
}

pub fn write_real_world_report(
    report: &TreeSitterRealWorldEvidenceReport,
    out_path: &Path,
) -> Result<()> {
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_path, serde_json::to_string_pretty(report)?)?;
    fs::write(
        out_path.with_extension("md"),
        render_real_world_markdown(report),
    )?;
    Ok(())
}

fn render_real_world_markdown(report: &TreeSitterRealWorldEvidenceReport) -> String {
    let mut output = String::new();
    output.push_str("# Tree-Sitter Real-World Evidence\n\n");
    output.push_str("> Generated by `cargo xtask certify tree-sitter --real-world`.\n\n");
    output.push_str(&format!(
        "- Profile: `{}`\n- Julie HEAD: `{}`\n- Verified repos: `{}`\n- Skipped repos: `{}`\n\n",
        report.profile,
        report.julie_head,
        report.verified_repos.len(),
        report.skipped_repos.len()
    ));
    output.push_str("| repo | language | status | files | language files | symbols | relationships | identifiers | types | diagnostic files | repo HEAD |\n");
    output.push_str("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |\n");
    for repo in &report.verified_repos {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} | {} | {} | {} | {} | {} | `{}` |\n",
            repo.repo_name,
            repo.language,
            repo.status,
            repo.file_count,
            repo.language_file_count,
            repo.symbol_count,
            repo.relationship_count,
            repo.identifier_count,
            repo.type_count,
            repo.parse_diagnostic_file_count,
            repo.repo_head.as_deref().unwrap_or("not-git")
        ));
    }
    if !report.skipped_repos.is_empty() {
        output.push_str("\n## Skipped Repos\n\n");
        for repo in &report.skipped_repos {
            output.push_str(&format!(
                "- `{}` (`{}`): {}\n",
                repo.repo_name, repo.language, repo.reason
            ));
        }
    }
    if !report.summary_flags.is_empty() {
        output.push_str("\n## Summary Flags\n\n");
        for flag in &report.summary_flags {
            output.push_str(&format!("- `{flag}`\n"));
        }
    }
    output
}
