use crate::tree_sitter_certification::TreeSitterCertificationReport;

pub fn render_tree_sitter_certification_markdown(report: &TreeSitterCertificationReport) -> String {
    let mut output = String::new();
    output.push_str("# Tree-Sitter Certification Report\n\n");
    output.push_str("> Generated by `cargo xtask certify tree-sitter`. Do not edit by hand.\n\n");
    output.push_str("## Summary\n\n");
    output.push_str("- Scope: checked-in tree-sitter evidence state\n");
    output.push_str(&format!(
        "- Registry rows: `{}`\n",
        report.registry_row_count
    ));
    output.push_str(&format!("- Golden fixtures: `{}`\n", report.fixture_count));
    output.push_str(&format!(
        "- Historical matrix rows: `{}`\n",
        report.historical_matrix_row_count
    ));
    output.push_str(&format!(
        "- Raw historical OSS reports: `{}`\n",
        report.raw_verification_report_count
    ));
    if let Some(evidence) = &report.real_world_evidence {
        output.push_str(&format!(
            "- Checked-in real-world verified repos: `{}`\n",
            evidence.verified_repo_count
        ));
        output.push_str(&format!(
            "- Checked-in real-world skipped repos: `{}`\n",
            evidence.skipped_repo_count
        ));
    } else {
        output.push_str("- Checked-in real-world verified repos: `0`\n");
        output.push_str("- Checked-in real-world skipped repos: `0`\n");
    }
    output.push_str(&format!(
        "- Rows with open gaps: `{}`\n",
        report.rows_with_open_gaps.len()
    ));
    output.push_str(&format!(
        "- Rows without gap entries: `{}`\n\n",
        report.rows_without_gap_entries.len()
    ));

    output.push_str("## Historical Coverage Delta\n\n");
    if report.historical_matrix_row_count == 0 && report.raw_verification_report_count == 0 {
        output.push_str(
            "Historical matrix evidence is deprecated; current capability, fixture, and real-world evidence are the source of truth.\n\n",
        );
    } else {
        output.push_str(&format!(
            "- Current registry rows missing from the restored historical matrix: {}\n",
            inline_code_list(&report.current_rows_missing_from_historical_matrix)
        ));
        output.push_str(&format!(
            "- Restored historical rows missing from the current registry: {}\n\n",
            inline_code_list(&report.historical_rows_missing_from_current_registry)
        ));
    }

    render_real_world_evidence(report, &mut output);

    output.push_str("## Fixture Evidence Totals\n\n");
    output.push_str("| symbols | relationships | pending | structured pending | identifiers | types | parse diagnostics |\n");
    output.push_str("| ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n");
    output.push_str(&format!(
        "| {} | {} | {} | {} | {} | {} | {} |\n\n",
        report.fixture_totals.symbols,
        report.fixture_totals.relationships,
        report.fixture_totals.pending_relationships,
        report.fixture_totals.structured_pending_relationships,
        report.fixture_totals.identifiers,
        report.fixture_totals.types,
        report.fixture_totals.parse_diagnostics
    ));

    output.push_str("## Kind Coverage Depth\n\n");
    output.push_str("| symbols | relationships | identifiers | body spans |\n");
    output.push_str("| ---: | ---: | ---: | ---: |\n");
    output.push_str(&format!(
        "| {} | {} | {} | {} |\n\n",
        report.kind_coverage_totals.symbols,
        report.kind_coverage_totals.relationships,
        report.kind_coverage_totals.identifiers,
        report.kind_coverage_totals.body_spans
    ));

    output.push_str("## Gap Counts\n\n");
    output.push_str("| capability | count |\n");
    output.push_str("| --- | ---: |\n");
    for (capability, count) in &report.gap_count_by_capability {
        output.push_str(&format!("| `{capability}` | {count} |\n"));
    }
    output.push('\n');

    output.push_str("## Open Capability Gaps\n\n");
    output.push_str("| language | capability | status | evidence | required closure |\n");
    output.push_str("| --- | --- | --- | --- | --- |\n");
    for gap in &report.open_gaps {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | {} |\n",
            gap.language,
            gap.capability,
            gap.status,
            gap.evidence,
            escape_table_cell(&gap.required_closure)
        ));
    }
    output.push('\n');

    output.push_str("## Per-Language Fixture Evidence\n\n");
    output.push_str("| language | parser | dependency | fixtures | symbols | relationships | pending | structured pending | identifiers | types | diagnostics | kind symbols | kind relationships | kind identifiers | kind body spans | gaps |\n");
    output.push_str(
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n",
    );
    for row in &report.language_rows {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            row.language,
            row.parser_crate,
            row.dependency_status,
            row.fixture_count,
            row.evidence.symbols,
            row.evidence.relationships,
            row.evidence.pending_relationships,
            row.evidence.structured_pending_relationships,
            row.evidence.identifiers,
            row.evidence.types,
            row.evidence.parse_diagnostics,
            row.kind_coverage.symbols,
            row.kind_coverage.relationships,
            row.kind_coverage.identifiers,
            row.kind_coverage.body_spans,
            row.gap_count
        ));
    }
    output.push('\n');

    output.push_str("## Rows Without Gap Entries\n\n");
    output.push_str(&format!(
        "{}\n",
        inline_code_list(&report.rows_without_gap_entries)
    ));

    output
}

fn render_real_world_evidence(report: &TreeSitterCertificationReport, output: &mut String) {
    output.push_str("## Checked-In Real-World OSS Evidence\n\n");
    let Some(evidence) = &report.real_world_evidence else {
        output.push_str(
            "No checked-in current real-world evidence file found at `docs/LANGUAGE_REAL_WORLD_EVIDENCE.json`.\n\n",
        );
        return;
    };

    output.push_str(&format!(
        "- Profile: `{}`\n- Julie HEAD recorded in evidence: `{}`\n- Summary flags: {}\n\n",
        evidence.profile,
        evidence.julie_head,
        inline_code_list(&evidence.summary_flags)
    ));
    output.push_str("| repo | language | status | files | language files | symbols | relationships | identifiers | types | diagnostic files | hard failures |\n");
    output.push_str("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |\n");
    for row in &evidence.rows {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            row.repo_name,
            row.language,
            row.status,
            row.file_count,
            row.language_file_count,
            row.symbol_count,
            row.relationship_count,
            row.identifier_count,
            row.type_count,
            row.parse_diagnostic_file_count,
            inline_code_list(&row.hard_failures)
        ));
    }
    output.push('\n');
}

fn inline_code_list(values: &[String]) -> String {
    if values.is_empty() {
        return "`none`".to_string();
    }
    values
        .iter()
        .map(|value| format!("`{value}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
